### ISSUE TITLE
Document Linux dependency on X11

### ISSUE THREAD

**Issue by dtoso-skymesh** [hoytech/Valence-p5#1]
Was trying to install this module inside Docker (build time) but a test failed. On further investigation, Electron binary itself is silently failing when no X11 `$DISPLAY` is available.

Most of the CPAN testers fail outputs have the same test failure so I guess they're failing for the same reason -- i.e: they don't have X11 available at module builds.

A workaround that relies on `Xvfb` is as follows:

```
RUN (Xvfb :1 &) && \
    export DISPLAY=":1" && \
    sleep 5 && \
    cpanm Valence && \
    rm -rf /tmp/.X*
```

Perhaps `Valence` should document this **build** dependency?

Obviously, the same applies for `Alien::Electron` and I'll raise the same issue there.

**Comment by hoytech** [comment]
Thanks! Added to the docs: 9e335c815ce7af424b4c6c34e8cb5bcc0ef41e8c
